config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users

  root 'welcome#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price,:image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalPro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'welcome/navbar' %>
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product,html: { multipart: true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :Picture %><br>
    <%= f.file_field :image %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Products</h1>
<div class="container">
  <div class="row">
      <% @products.each do |product| %>
        <div class="col-md-4">
          <div class="card">
          <%= image_tag product.image.url(:medium) ,class:'card-img-top'%>
          <div class="card-block">
            <h4 class="card-title"><%= product.name %></h4>
            <button class="btn btn-primary">Buy RS:<%=product.price %></button> 
          </div>
          </div>
        </div> 
    <% end %>
</div>  
</div>





<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="col-md-4">
	<%= image_tag @product.image.url(:medium) ,class:'img-responsive'%>
	<h3><%= @product.name %></h3>
	<p><%= @product.description %></p>
	<SPAN><%= @product.price %></SPAN>
</div>

<p id="notice"><%= notice %></p>

app/views/welcome/_navbar.html.erb
<nav class="navbar navbar-light bg-faded">
<%= link_to "Home", root_path,class: 'navbar-brand' %>
  <ul class="nav navbar-nav float-xl-right">
    <%- if user_signed_in? %>
     <li class="nav-item "> <%= link_to "logout", destroy_user_session_path , method: :delete,class:"nav-link"  %></li>
    <% else %>
     <li class="nav-item"> <%= link_to "login", new_user_session_path ,class: "nav-link" %></li>
     <li class="nav-item"><%= link_to "signup", new_user_registration_path,class: "nav-link"  %></li>
    <% end %>
   </ul>
</nav>

app/views/welcome/index.html.erb
<div class="banner">
	
</div>
<div class="container">
		
	<div class="embed-responsive embed-responsive-4by3 add">
	<iframe width="100" height="200" class="embed-responsive-item" src="https://www.youtube.com/embed/YjmHewtNrqU" frameborder="0"></iframe>
	</div>
</div>